youtube_analytics:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: dummy
      user: dummy
      password: dummy
      role: ACCOUNTADMIN
      database: RAW_DB
      warehouse: COMPUTE_WH
      schema: PUBLIC
      threads: 4
